# Spring configuration properties
spring:
  application:
    name: aquariux_assignment_wjh
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql
  h2:
    console:
      enabled: true
