# Spring configuration properties
spring:
  application:
    name: aquariux_assignment_wjh
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password:
  h2:
    console:
      enabled: true
