INSERT INTO APP_USER (USERNAME, CREATED_AT, UPDATED_AT) VALUES('John Doe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER_WALLET (USER_ID, CREATED_AT, UPDATED_AT) VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WALLET_BALANCES (WALLET_ID, TICKER_SYMBOL, BALANCE) VALUES (1, 'USDT', 50000.00);